function renderAds(D, $, gname, nice){
  const A = D.ads; const c = $("ads-section"); if (!A || !A.footprint){ c.innerHTML = "<p class='small'>Products analysis not yet available.</p>"; return; }
  const F = A.footprint, W = A.ad_windows, CB = A.control_baseline;
  const html = [];
  html.push(`<p>Sponsor reads are the one place where health claims are scripted, repeated across shows, and attached to a product. Markers such as "brought to you by", "promo code" and "dot com slash" locate them; an <b>ad window</b> is any matched sentence within four sentences of a marker (or of a product mention that itself sits in such a window).</p>`);
  html.push(`<div class="tiles"><div class="tile"><div class="v">${F.share_episodes_with_commercial_marker_pct.toFixed(0)}%</div><div class="k">of episodes contain a sponsor-read marker</div></div><div class="tile"><div class="v">${fmt(F.commercial_sentences)}</div><div class="k">marker sentences, ${F.commercial_per_1000_sentences_overall.toFixed(1)} per 1,000</div></div><div class="tile"><div class="v">${A.summary.share_episodes_naming_a_health_product_pct.toFixed(0)}%</div><div class="k">of episodes name at least one health product</div></div><div class="tile"><div class="v">${W.share_health_topic_sentences_in_ad_windows_pct.toFixed(1)}%</div><div class="k">of health-topic sentences sit inside an ad window</div></div><div class="tile"><div class="v">${W.share_study_citation_in_ad_windows_pct.toFixed(0)}%</div><div class="k">of "studies show" sentences sit inside an ad window</div></div></div>`);
  html.push(`<div class="grid2"><figure><p class="fig-title">Sponsor-read density by genre</p><p class="fig-sub">Marker sentences per 1,000 sentences; right-hand figure is share of episodes with any marker</p><div id="fig-ad-genre"></div><figcaption>News shows are the most ad-dense because their episodes are short; sports and comedy have a sponsor in nearly nine of ten episodes but at low density. Meditation and sleep feeds top the per-show list, where the read is a large share of a short episode.</figcaption></figure>
  <figure><p class="fig-title">Where sponsor reads sit in an episode</p><p class="fig-sub">Share of marker sentences by decile of episode position</p><div id="fig-ad-pos"></div><figcaption>A quarter of all marker sentences fall in the first tenth of the episode and a tenth in the final tenth: the pre-roll, mid-roll, outro shape. Health-chart shows front-load harder (32% in the first decile against 24% elsewhere).</figcaption></figure></div>`);
  html.push(`<h3>Which products</h3><p>Ninety of the 94 health-related products in the lexicon appear. BetterHelp is in a class of its own: ${fmt(A.health_products[0].episodes)} episodes across ${A.health_products[0].shows} shows, roughly one episode in fifteen corpus-wide, and 90% of its sentences are verbatim repeats of scripted copy. Whoop, AG1, Wegovy, Headspace, Helix Sleep and Peloton follow. Reach and concentration differ: Headspace and Whoop are spread across 160+ shows with no show above a tenth of mentions, while Relief Factor is 87% Charlie Kirk, David Protein 72% Huberman Lab, Alpha Brain 70% Rogan, Organifi 66% Mind Pump and Paleo Valley 54% Dr. Jockers. The most show-concentrated products are the political-show sponsors (Relief Factor, Good Ranchers, Balance of Nature) and host-affiliated brands.</p>
  <figure><p class="fig-title">Health-related products by episodes mentioned</p><p class="fig-sub">Top 30; right-hand figure is number of shows</p><div id="fig-products"></div><figcaption>"Momentous" and "Ritual" are inflated by the ordinary words and are kept here only for transparency; "Wegovy" counts include both editorial and sponsored mentions. LMNT is absent because ASR renders it as "element".</figcaption></figure>`);
  html.push(`<h3>Health claims inside ad windows</h3><p>Overall, 5% of health-topic sentences are ad-borne, so most health talk is editorial. But the composition of what is said near a sponsor read differs sharply from the rest of the corpus, and for a few topics the sponsor read is the main channel.</p>
  <figure><p class="fig-title">Most ad-borne topics</p><p class="fig-sub">Share of each topic's sentences that fall inside an ad window</p><div id="fig-adborne"></div><figcaption>GLP-1 drugs, EMF and technology exposure, AI health information, supplements and biohacking are the topics listeners hear most often from sponsors (Wegovy reads, phone and sleep-device reads, AI apps, supplement reads). The contested editorial topics, autism, performance drugs, substance use and manosphere health, are almost never ad-borne.</figcaption></figure>
  <div class="grid2"><figure><p class="fig-title">Health-product versus generic-product neighbourhoods</p><p class="fig-sub">Share of matched sentences within four sentences of a product mention</p><div id="fig-control"></div><figcaption>Sentences around a health product are health-topic sentences ${CB.health_products.health_topic_pct.toFixed(0)}% of the time against ${CB.control_products.health_topic_pct.toFixed(1)}% around generic sponsors (Shopify, Squarespace, Quince, SimpliSafe, ExpressVPN), and carry explicit strength claims ("clinically proven") at ${(CB.health_products.strength_claim_pct/CB.control_products.strength_claim_pct).toFixed(0)} times the rate. Absolute-certainty markers do not differ, so the gap is specifically health assertion and borrowed evidence, not emphatic ad language.</figcaption></figure>
  <figure><p class="fig-title">Products whose neighbourhoods carry the most evidence language</p><p class="fig-sub">Share of sentences near the product with an evidence-axis marker; products with 100+ neighbourhood sentences</p><div id="fig-evidence-products"></div><figcaption>Supplements and tests, not devices, lead: their copy leans on "clinically proven", "backed by science" and "studies show".</figcaption></figure></div>`);
  html.push(`<p>Representative claims made inside ad windows:</p><div class="ex">` + A.ad_health_claim_examples.slice(0,8).map(e=>`<div class="quote">${esc(e.text)}<span class="src">${esc(e.product)} · ${esc(e.show)}</span></div>`).join("") + `</div>`);
  html.push(`<p>Two implications for the pipeline. First, the product-mention dimension and the <i>advertisement</i> relevance flag will be doing real work: scripted reads are a large, repetitive, claim-dense stratum that should be sampled and verified as a block rather than sentence by sentence (one BetterHelp line appears ${fmt(A.repetition[0].top_repeated[0].count)} times). Second, evidence-verification of ad copy is tractable because the claims recur verbatim across shows; verifying a few hundred distinct sponsor sentences covers tens of thousands of airings.</p>`);
  c.innerHTML = html.join("");
  hbar("fig-ad-genre", F.by_genre.slice().sort((a,b)=>b.commercial_per_1000-a.commercial_per_1000).map(r=>({label:gname(r.genre_group), value:r.commercial_per_1000, sub:r.share_episodes_with_ad_pct.toFixed(0)+"% eps", tip:`${r.commercial_per_1000.toFixed(2)} per 1,000 · ${r.share_episodes_with_ad_pct.toFixed(0)}% of episodes have a marker`})), {labelWidth:180, rowH:20, digits:1});
  { const c2=$("fig-ad-pos"); const o=A.ad_position.overall, hcs=A.ad_position.health_chart_shows, ot=A.ad_position.other_shows; lines(c2, {x:o.map(r=>`${r.decile*10}–${r.decile*10+10}%`), series:{"all shows":o.map(r=>r.share_pct), "Health & Fitness chart":hcs.map(r=>r.share_pct), "other shows":ot.map(r=>r.share_pct)}}, {unit:"%", digits:1, height:220, ticks:10}); }
  hbar("fig-products", A.health_products.slice(0,30).map(r=>({label:nice(r.product), value:r.episodes, sub:r.shows+" shows", tip:`${fmt(r.episodes)} episodes · ${r.shows} shows · ${r.type} · ${r.share_sentences_with_commercial_marker_pct.toFixed(0)}% of sentences carry an ad marker`})), {labelWidth:170, rowH:18});
  hbar("fig-adborne", A.ad_borne_topics.slice(0,16).map(r=>({label:nice(r.topic).slice(0,42), value:r.share_pct, sub:fmt(r.sentences)+" sent.", tip:`${r.share_pct.toFixed(1)}% of ${fmt(r.sentences)} sentences in ad windows`})), {labelWidth:300, rowH:18, unit:"%", digits:1});
  { const c3=$("fig-control"); const H=CB.health_products, C=CB.control_products; const rows=[["health-topic sentences",H.health_topic_pct,C.health_topic_pct],["any evidence marker",H.evidence_pct,C.evidence_pct],["strength claim (clinically proven…)",H.strength_claim_pct,C.strength_claim_pct],["absolute certainty",H.absolute_certainty_pct,C.absolute_certainty_pct]];
    const W=480, rh=30, lw=230, Hh=rows.length*rh+24; const svg=el("svg",{viewBox:`0 0 ${W} ${Hh}`,width:"100%"},c3); const max=40; const sx=v=>lw+(W-lw-40)*Math.min(v,max)/max; const g=el("g",{class:"grid"},svg); for(let i=0;i<=4;i++){const v=max*i/4; el("line",{x1:sx(v),x2:sx(v),y1:0,y2:Hh-20},g); txt(svg,sx(v),Hh-6,v+"%",{"text-anchor":"middle",class:"num muted"});}
    rows.forEach((r,i)=>{const y=i*rh; txt(svg,lw-8,y+rh*0.62,r[0],{"text-anchor":"end",class:"lbl"}); const a=el("rect",{x:lw,y:y+4,width:Math.max(1.5,sx(r[1])-lw),height:9,fill:"var(--s1)"},svg); const b=el("rect",{x:lw,y:y+15,width:Math.max(1.5,sx(r[2])-lw),height:9,fill:"var(--s2)"},svg); txt(svg,sx(r[1])+4,y+12,r[1].toFixed(r[1]<1?2:1)+"%",{class:"num","font-size":"10px"}); txt(svg,sx(r[2])+4,y+23,r[2].toFixed(r[2]<1?2:1)+"%",{class:"num","font-size":"10px"}); });
    const lg=document.createElement("div"); lg.className="legend"; lg.innerHTML=`<span><i style="background:var(--s1)"></i>near health products (63)</span><span><i style="background:var(--s2)"></i>near generic sponsors (11)</span>`; c3.appendChild(lg); }
  hbar("fig-evidence-products", A.product_evidence_leaders.filter(r=>r.product!=="ritual").slice(0,14).map(r=>({label:nice(r.product), value:r.evidence_pct, sub:fmt(r.neighbourhood_sentences)+" sent.", tip:`${r.evidence_pct.toFixed(1)}% evidence language · ${r.strength_claim_pct.toFixed(1)}% strength claims · ${r.type}`})), {labelWidth:170, rowH:18, unit:"%", digits:1});
}
function renderAudit(D, $, gname, nice){
  const c = $("audit-section"); const AN = D.audit_narr || {}, AL = D.audit_labels || {}; const sn = AN._summary, sl = AL._summary;
  const html = [];
  html.push(`<p>A blinded sample of matched sentences (20 per narrative, frame, evidence, distrust and correction label; 8 to 10 per topic) was graded by hand for whether the sentence genuinely invokes the label, and, for narratives, for the speaker's stance. Grades are in <code>audit_narratives.json</code>, <code>audit_labels.json</code> and the accompanying row files.</p>`);
  if (!sn && !sl){ html.push(`<p class="small">Audit results are still being produced; this section will be filled in when they land.</p>`); c.innerHTML = html.join(""); return; }
  if (sl){
    const bySec = sl.precision_by_section || sl.overall_precision_by_section || sl.by_section || {};
    html.push(`<h3>Topic, frame and evidence labels</h3>`);
    const secRows = Object.entries(bySec).map(([k,v])=>({sec:k, p: typeof v==="number"? v : (v.precision!==undefined? v.precision : v)}));
    if (secRows.length) html.push(`<div class="tiles">` + secRows.map(r=>`<div class="tile"><div class="v">${(r.p<=1? r.p*100 : r.p).toFixed(0)}%</div><div class="k">precision, ${esc(r.sec)} labels</div></div>`).join("") + `</div>`);
    const low = Object.entries(AL).filter(([k,v])=>k!=="_summary" && v.n>=8).sort((a,b)=>a[1].precision-b[1].precision).slice(0,14);
    html.push(`<div id="audit-labels-table"></div>`);
    const obs = sl.observations || sl.qualitative_observations || sl.notes || [];
    if (obs.length || typeof obs==="string") html.push(`<p class="small">${Array.isArray(obs)? obs.map(esc).join(" ") : esc(obs)}</p>`);
    const bad = sl.worst_terms_recommend_removal || sl.false_positive_terms || sl.terms_to_remove;
    if (bad) html.push(`<p class="small"><b>Terms flagged for removal:</b> ${esc(Array.isArray(bad)? bad.map(x=>typeof x==="string"?x:(x.term||JSON.stringify(x))).join(", ") : JSON.stringify(bad))}</p>`);
    setTimeout(()=>{ table("audit-labels-table", [{h:"Label",k:r=>nice(r.label.replace(/^[a-z]+:/,"")) + " ("+r.label.split(":")[0]+")"},{h:"n",k:"n",n:true},{h:"Precision",k:r=>Math.round(r.precision*100)+"%",n:true},{h:"Substantive",k:r=>r.substantive!=null? Math.round(100*r.substantive/Math.max(1,r.n))+"%":"–",n:true},{h:"Main false-positive pattern",k:"note"}], low.map(([k,v])=>Object.assign({label:k},v))); }, 0);
    html.push(`<p>Precision is a property of label type, not of the method. Concrete health-noun topics (vaccines, menopause, parasite cleanse, stem cells, toxins, inflammation, longevity) score 95 to 100%. Labels built from idioms (conflict of interest, anti-expert populism, government distrust, cover-up, correction) score near zero <i>when judged on the bare sentence</i>, because the corpus is full of political, true-crime and personal-finance shows where those phrases are routine. Two consequences for reading this report: the framing rates in section 8 are computed only on sentences that also contain a health-topic term, which removes most but not all of that leakage; and raw counts for <i>emf_technology_exposure</i> (mostly "5G" phone-carrier ads), <i>ai_health_information</i> (OpenAI sponsor reads) and the correction labels should be treated as unreliable. Only 52% of topic hits are substantive discussion; the rest are passing mentions, jokes or ad copy, so the 1.6% health-sentence share overstates real health discussion by about half.</p>`);
  }
  if (sn){
    html.push(`<h3>Narratives</h3>`);
    const rel = Object.entries(AN).filter(([k])=>k!=="_summary"); const tot = rel.reduce((a,[k,v])=>a+v.n,0), totr = rel.reduce((a,[k,v])=>a+v.relevant,0);
    const st = rel.reduce((a,[k,v])=>{ for (const s in v.stance) a[s]=(a[s]||0)+v.stance[s]; return a; },{});
    html.push(`<div class="tiles"><div class="tile"><div class="v">${Math.round(100*totr/tot)}%</div><div class="k">pooled precision over ${tot} graded narrative sentences</div></div>` + ["endorse","report","rebut","ad","unclear"].map(s=>`<div class="tile"><div class="v">${Math.round(100*(st[s]||0)/Math.max(1,totr))}%</div><div class="k">of relevant sentences: ${s}</div></div>`).join("") + `</div>`);
    html.push(`<figure><p class="fig-title">Stance mix per narrative</p><p class="fig-sub">Share of relevant sampled sentences; narratives with at least 10 relevant sentences</p><div id="fig-stance"></div><figcaption>Endorsement dominates the wellness narratives; the vaccine and COVID narratives are more often reported or rebutted, which is consistent with their political-show home. "Ad" marks sponsor reads.</figcaption></figure>`);
    const obs = sn.observations || sn.qualitative_observations || sn.notes || [];
    html.push(`<p class="small">${Array.isArray(obs)? obs.map(esc).join(" ") : esc(String(obs))}</p>`);
    const low = sn.lowest_precision || sn.lowest_precision_narratives || [];
    if (low.length) html.push(`<p class="small"><b>Lowest-precision narratives:</b> ${low.map(x=>esc(typeof x==="string"? x : (x.label||x.narrative||"") + (x.precision!==undefined? ` (${Math.round(x.precision*100)}%)`:""))).join("; ")}. Their counts in section 7 should be read with that discount, and "died suddenly" in particular is mostly ordinary obituary language.</p>`);
    setTimeout(()=>{
      const rows = rel.filter(([k,v])=>v.relevant>=10).sort((a,b)=>(b[1].stance.endorse/b[1].relevant)-(a[1].stance.endorse/a[1].relevant));
      const c2=$("fig-stance"); const W=900, rh=17, lw=260, H=rows.length*rh+24; const svg=el("svg",{viewBox:`0 0 ${W} ${H}`,width:"100%"},c2); const sx=v=>lw+(W-lw-30)*v; const cols={endorse:"--s8",report:"--s1",rebut:"--s3",ad:"--s4",unclear:"--seq2"};
      for(let i=0;i<=4;i++){txt(svg,sx(i/4),H-6,(i*25)+"%",{"text-anchor":"middle",class:"num muted"});}
      rows.forEach(([k,v],i)=>{const y=i*rh; txt(svg,lw-8,y+rh*0.72,nice(k).slice(0,40),{"text-anchor":"end",class:"lbl","font-size":"11px"}); let x=0; ["endorse","report","rebut","ad","unclear"].forEach(s=>{const w=(v.stance[s]||0)/v.relevant; if(w>0){const r=el("rect",{x:sx(x)+ (x>0?1:0),y:y+3,width:Math.max(0,sx(x+w)-sx(x)-1),height:rh-6,fill:`var(${cols[s]})`},svg); r.addEventListener("mousemove",e=>showTip(e,`<b>${nice(k)}</b><br>${s}: ${v.stance[s]} of ${v.relevant} relevant (precision ${Math.round(v.precision*100)}%)<br>${esc(v.note||"")}`)); r.addEventListener("mouseleave",hideTip);} x+=w;}); });
      const lg=document.createElement("div"); lg.className="legend"; lg.innerHTML=Object.entries(cols).map(([s,cv])=>`<span><i style="background:var(${cv})"></i>${s}</span>`).join(""); c2.appendChild(lg);
    },0);
  }
  c.innerHTML = html.join("");
}
function renderPilot(D, $, gname, nice){
  const P = D.pilot; const c = $("pilot-section"); if (!P || !P.coverage_and_cost) return;
  const C = P.coverage_and_cost, F = P.findings, K = P.keyword_scan_agreement, S = C.spend, X = C.extrapolation;
  const html = [];
  html.push(`<div class="tiles"><div class="tile"><div class="v">$${S.cost_usd.toFixed(2)}</div><div class="k">spent (guard cap $4.50), ${S.requests} requests</div></div><div class="tile"><div class="v">${C.windows_labeled}</div><div class="k">windows accepted of ${C.windows_prepared} prepared (${C.episodes} episodes)</div></div><div class="tile"><div class="v">$${C.cost_per_accepted_window_usd.toFixed(3)}</div><div class="k">per accepted 900-word window</div></div><div class="tile"><div class="v">${F.claims_total}</div><div class="k">atomic claims extracted</div></div><div class="tile"><div class="v">${F.product_mentions_total}</div><div class="k">product mentions</div></div><div class="tile"><div class="v">${Math.round(100*C.cache_hit_share_of_input)}%</div><div class="k">of input tokens were cache hits</div></div></div>`);
  html.push(`<p><b>Setup.</b> The hosted API exposes the model as <code>deepseek-v4-flash</code> and serves the Responses route with strict JSON Schema and <code>reasoning.effort</code>, so the pipeline ran unmodified over its preferred route with <code>reasoning_effort=low</code> and batch size 4. The spending guard in <code>usage-limits.toml</code> was declared at DeepSeek's peak prices and stopped the run at $4.48, as designed. The API key lives only in the git-ignored <code>.env</code>.</p>`);
  html.push(`<p><b>Cost.</b> The observed price is about four cents per accepted window, but the run bought 107 windows with 203 requests, so most of the spend went to responses that failed validation and were retried one window at a time. The manifest cannot say which rejection kinds dominated, because the budget stop overwrote each window's earlier state, and that number is what the cost model turns on. Taken at face value, labeling the live-window episodes of the 24 densest health shows (${fmt(X.top24_health_shows_windows)} windows) would cost about $${fmt(X.top24_health_shows_usd)} at peak rates and half that off-peak; the whole corpus (${fmt(X.whole_corpus_windows)} windows) about $${fmt(X.whole_corpus_usd)}. A clean run with the rejection rate fixed, or with thinking off where the acceptance rate allows, would be several times cheaper.</p>`);
  const pg = F.per_group || {}; const rows = Object.entries(pg).map(([g,v])=>Object.assign({group:g}, v));
  html.push(`<h3>What the model extracted</h3><p>Yield separates show types cleanly. Wellness episodes produced about five checkable claims per window and one product mention per window; debunking shows two and a half claims; general-audience and political episodes about one claim every two windows. The scan's contrast between wellness and political health talk (section 5) is therefore also a contrast in claim density: political vaccine talk is mostly not made of atomic claims.</p><div id="pilot-groups"></div>`);
  html.push(`<div class="grid2"><figure><p class="fig-title">Claims by type</p><div id="fig-pilot-types"></div></figure><figure><p class="fig-title">Claims by expressed certainty</p><div id="fig-pilot-cert"></div><figcaption>Certainty is coded from verbatim marker words; two thirds of claims are plain unhedged declaratives. Every claim carries the high-recall <i>possible_misinformation</i> screening flag by design, so the flag conveys no information on this sample.</figcaption></figure></div>`);
  html.push(`<p>Example claims, chosen across groups:</p><div class="ex">` + (P.example_claims||[]).slice(0,10).map(e=>`<div class="quote">${esc(e.claim_text)}<span class="src">${esc(e.show)} · ${esc(e.claim_type)} · ${esc(e.expressed_certainty)}${e.certainty_markers&&e.certainty_markers.length?" ("+esc(e.certainty_markers.join(", "))+")":""} · ${esc(e.discourse_role)}${e.scan_narrative_hit_in_episode?" · scan narrative hit in episode":""}</span></div>`).join("") + `</div>`);
  html.push(`<h3>Keyword scan against the model's labels</h3><p>At the episode-by-topic level, the scan found ${K.pairs_both} of the ${K.pairs_both + K.pairs_llm_only} episode-topic pairs the model labeled (recall ${K.scan_recall_overall.toFixed(2)}), and ${K.pairs_scan_only} pairs the model did not label (precision ${K.scan_precision_overall.toFixed(2)}). The precision figure is a lower bound and should not be quoted as such: the model saw only 36% of the prepared windows and only 14 of the 24 episodes, while the scan covers every sentence of every episode, so most "scan only" pairs are simply parts of the episode the model never read. The recall direction is informative: the model labeled COVID and health-system-trust content in windows where the scan had no hit, and the scan fires on cardiometabolic, weight-loss and alcohol vocabulary in episodes where the model labels nothing, which matches the audit's finding that those topics carry many passing mentions.</p><div id="pilot-agree"></div>`);
  html.push(`<div class="callout warn"><p><b>Pipeline bug found by the pilot.</b> <code>merge</code> cannot run on this or any current run: it re-validates stored window results with the raw-payload validator, but <code>label</code> stores normalised results carrying the derived <code>axis</code> field, which that validator forbids (<code>topic_labeling.py</code> around lines 1232 to 1247 and 1519). The analysis therefore read the window labels directly, so totals above count overlap duplicates twice; per-window rates are unaffected. This needs a fix before any production run.</p></div>`);
  c.innerHTML = html.join("");
  table("pilot-groups", [{h:"Show group",k:"group"},{h:"Windows",k:"windows",n:true},{h:"Annotations / window",k:"annotations_per_window",n:true,d:2},{h:"Claims / window",k:"claims_per_window",n:true,d:2},{h:"Products / window",k:"products_per_window",n:true,d:2}], rows.sort((a,b)=>(b.claims_per_window||0)-(a.claims_per_window||0)));
  hbar("fig-pilot-types", Object.entries(F.claims_by_type||{}).sort((a,b)=>b[1]-a[1]).map(([k,v])=>({label:nice(k), value:v})), {labelWidth:180, rowH:20});
  hbar("fig-pilot-cert", ["absolute","unhedged","hedged","speculative"].filter(k=>(F.claims_by_expressed_certainty||{})[k]!=null).map(k=>({label:k, value:F.claims_by_expressed_certainty[k]})), {labelWidth:120, rowH:22, color:"--s2"});
  const pt = (K.per_topic||[]).filter(r=>r.episodes_llm>=2).sort((a,b)=>b.episodes_llm-a.episodes_llm).slice(0,16);
  table("pilot-agree", [{h:"Topic",k:r=>nice(r.topic)},{h:"Episodes (model)",k:"episodes_llm",n:true},{h:"Episodes (scan)",k:"episodes_scan",n:true},{h:"Both",k:"both",n:true},{h:"Scan recall",k:r=>r.scan_recall.toFixed(2),n:true}], pt);
}
