"""Forget ASR transcripts so ``transcribe`` runs again on the same episodes.

Publisher (RSS) transcripts are never touched: they are not regenerated by
the model, so deleting them would only lose data.
"""

from __future__ import annotations

import logging
import sqlite3
from pathlib import Path

from podcast_pipeline import db
from podcast_pipeline.config import Config

logger = logging.getLogger(__name__)


def run(config: Config, conn: sqlite3.Connection, episode_ids: list[int] | None = None,
        podcast_ids: list[int] | None = None, everything: bool = False,
        keep_files: bool = False, dry_run: bool = False) -> dict:
    if not (episode_ids or podcast_ids or everything):
        raise ValueError("nothing selected: pass episode ids, podcast ids, or everything=True")

    conditions = ["e.has_rss_transcript = 0", "e.transcript_file_path IS NOT NULL"]
    params: list = []
    if episode_ids:
        conditions.append(f"e.id IN ({','.join('?' * len(episode_ids))})")
        params += episode_ids
    if podcast_ids:
        conditions.append(f"e.podcast_id IN ({','.join('?' * len(podcast_ids))})")
        params += podcast_ids
    rows = conn.execute(f"SELECT e.id, e.transcript_file_path FROM episodes e "
                        f"WHERE {' AND '.join(conditions)}", params).fetchall()

    stats = {"selected": len(rows), "reset": 0, "files_deleted": 0, "dry_run": dry_run}
    if dry_run:
        logger.info(f"Would reset {len(rows)} episodes: {[r['id'] for r in rows[:50]]}")
        return stats

    for row in rows:
        db.delete_transcript(conn, row["id"])
        stats["reset"] += 1
    conn.commit()

    if not keep_files:
        for row in rows:
            path = Path(row["transcript_file_path"])
            if path.exists():
                path.unlink()
                stats["files_deleted"] += 1
    logger.info(f"Reset complete: {stats}")
    return stats
